### ISSUE TITLE
Able to backup, but permissions issue running as a container.

### ISSUE THREAD

**Issue by slimshizn** [steefdebruijn/docker-roonserver#10]
Since there have been updates to Roon, every build has reset all settings to default and removed libraries/services. This can be a PITA if your library is massive. 

Trying to restore a backup, I would run into permission issues which would force the container to stop.

I tried to give all files a chmod 777, or make sure that the user was correct which did not seem to work.

**Comment by steefdebruijn** [comment]
Hi

I *guess* that you have pointed `/app` and `/data` to one and the same physical *folder*.

If so, you should not do that!
* `/app` is managed by the updater, and
* `/data` is managed by the core (not the updater)

By pointing them to the same physical folder these apps (core and updater) can (and propably will) mess up eachothers files and/or permissions.

Steef

**Comment by steefdebruijn** [comment]
Just pushed an update image that checks on startup the above issue and refuses to start if this is detected.
Please report back if you had this situation, and if separating them solves your issue on next core update.
