### ISSUE TITLE
Upcoming Roon Linux Performance Changes

### ISSUE THREAD

**Issue by joltman80** [steefdebruijn/docker-roonserver#13]
I received an email today from Roon stating that they were making changes to Roon server to increase Linux performance.  These changes involve installing other software.  I wanted to create an issue here with the link in hopes that the docker container you built will be updated accordingly.  Thanks for the container, it works great!

https://help.roonlabs.com/portal/en/kb/articles/linux-performance-improvements

**Comment by daemonp** [comment]
It does look like the library is installed in the container by default, I suspect it will just work when the new version of roon is rolled out.

`apt list --installed | grep libicu`

```
libicu63/oldstable,oldstable,now 63.1-6+deb10u1 amd64 [installed,automatic]
 ```

In the kb article they reference a newer version but I don't think that should be an issue. I just applied for the beta and will load it into the live container when approved.

**Comment by steefdebruijn** [comment]
I did install the beta last night and it runs on a charm
