### ISSUE TITLE
Where is the "external volume"

### ISSUE THREAD

**Issue by zbigbird** [steefdebruijn/docker-roonserver#17]
Hi,dear.Thanks for your share.Where directory should I put the application files to?
I have download Roonserver Application (an earlier version,the file name is RoonServer_linuxx64.tar.bz2). Accord to the thread ,I put the application (RoonServer_linuxx64.tar.bz2) to /app directory. But when I pull the docker ,it download a newer version application from Roonlab site. Please give some advice:
1、Could I use my own lower version application to deploy a docker ? How can I keep this version when I update the docker?
2、Where should I put the lower version application ?
Thank you very much

**Comment by steefdebruijn** [comment]
The `run.sh` script in the image only downloads Roon server binary when is is not present.
So, if you extract your own version in the `/app` folder (or presumably the host folder mapped to `/app` in the container) it will skip the download.
