### ISSUE TITLE
issue with docker?

### ISSUE THREAD

**Issue by heapxor** [steefdebruijn/docker-roonserver#4]
docker run --daemon  --net=host   -e TZ="Europe/Amsterdam"  -v roon-app:/opt/RoonServer/app  -v roon-data:/opt/RoonServer/data -v roon-music:/opt/RoonServer/music -v roon-backups:/opt/RoonServer/backup steefdebruijn/docker-roonserver:latest
unknown flag: --daemon
See 'docker run --help'.

Docker version 18.06.1-ce, build e68fc7a

**Comment by heapxor** [comment]
system Description:    Ubuntu 18.04.2 LTS

**Comment by steefdebruijn** [comment]
See docker documentation for `run` command at https://docs.docker.com/engine/reference/run/

Use `-d` which stands for detached.

**Comment by heapxor** [comment]
yeah, maybe the main page should be upgraded accordingly.

**Comment by steefdebruijn** [comment]
duh. thx. fixed. :-)
