### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by leshokunin** [steefdebruijn/docker-roonserver#6]
No issue here, just wanted to say thanks for making the Docker image. It was surprisingly easy to setup :)

By the way, how up to date do you expect it to remain?

**Comment by steefdebruijn** [comment]
Thanks 👍 

The image itself contains only a downloader and some system requirements for the roon server. I update it very infrequently.

The Roon server software updates itself. The only known issue is that this is known *not* to work on unraid installations; I have no knowledge and/or resources to investigate this problem.

Steef
