### ISSUE TITLE
RoonServer port?

### ISSUE THREAD

**Issue by xthursdayx** [steefdebruijn/docker-roonserver#7]
Do you happen to know what port(s) Roon Server uses? My network is set up in a way that only allows me to open individual ports, so it would be helpful to know what port or range of ports to open. Cheers!

**Comment by steefdebruijn** [comment]
According to the roon community forums https://community.roonlabs.com/t/cant-find-roon-core-from-remote/1098/7 you should open/forward:

* UDP port 9003
* TCP ports 9100-9200

I did not test this. Please let me know if this is working. I guess you can/should/must omit the `--net=host` startup option if you use this.

**Comment by xthursdayx** [comment]
Thanks a lot! I'll try this out when I get a chance and report back. Cheers.

**Comment by xthursdayx** [comment]
It looks like this worked. Thanks!
